FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el archivo de dependencias del backend
COPY backend/pyproject.toml .

# Instalamos dependencias principales (puedes luego mejorar esto usando `pip install .`)
RUN pip install --no-cache-dir --upgrade pip \
    && pip install google-adk google-generativeai  google-cloud-bigquery python-dotenv

# Copiamos el código del backend dentro del contenedor
COPY backend/src ./src

# Copiamos el agents al directorio raíz
COPY backend/agents ./agents

# Copiamos el script de prueba
COPY backend/test_bigquery.py .

# Aseguramos que Python pueda encontrar el paquete raíz `infrastructure`, `application`, etc.
ENV PYTHONPATH=/app/src:/app

EXPOSE 8080

# Levantamos el servidor del agente de Google ADK
CMD ["adk", "web", "agents", "--host", "0.0.0.0", "--port", "8080"]